apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./porsgresServices/HeadlessClusterIP.yml
- ./porsgresServices/PostgresSecret.yml
- ./porsgresServices/StatefullSetPorsgres.yml
- ./manifest/ConfigMap.yml
- ./manifest/Ingress.yml
- ./manifest/AnalysisTemplateCPU.yml
- ./manifest/RolloutPong.yml
- ./manifest/Rollout.yml
- ./manifest/ingress-gateway.yml
- ./manifest/LogOutputClusterIP.yml
- ./manifest/PingPongClusterIP.yml
- ./manifest/greeter/DeploymentGreeterV1.yml
- ./manifest/greeter/DeploymentGreeterV2.yml
- ./manifest/greeter/GreeterService.yml
- ./manifest/greeter/GreeterServiceV1.yml
- ./manifest/greeter/GreeterServiceV2.yml
- ./manifest/greeter/GreeterGateway.yml
- ./manifest/greeter/GreeterVirtualService.yml
- ./manifest/greeter/GreeterDestinationRuleV1.yml
- ./manifest/greeter/GreeterDestinationRuleV2.yml
- ./persistentVolumes/persistentvolume.yaml
- ./persistentVolumes/persistentvolumeclaim.yaml

  
images:
- name: EXCERSISES/PING_PONG
  newName: zelhs/randomstring
  newTag: main-cb280ca550e49dcb41f88e4807527cc7cdee59f6
- name: EXCERSISES/RANDOM_STRING
  newName: zelhs/ping-pong-application
  newTag: main-cb280ca550e49dcb41f88e4807527cc7cdee59f6
- name: EXCERSISES/greeter
  newName: zelhs/greeter
  newTag: main-cb280ca550e49dcb41f88e4807527cc7cdee59f6
