apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./porsgresServices/HeadlessClusterIP.yml
- ./porsgresServices/PostgresSecret.yml
- ./porsgresServices/StatefullSetPorsgres.yml
- ./manifest/ConfigMap.yml
- ./manifest/KnativeGetStringServer.yml
- ./manifest/KnativePingPong.yml
- ./manifest/Ingress.yml
- ./manifest/AnalysisTemplateCPU.yml
- ./manifest/KnativeLogoutput.yml
- ./manifest/greeter/KnativeGreeter.yml
- ./persistentVolumes/persistentvolume.yaml
- ./persistentVolumes/persistentvolumeclaim.yaml

  
images:
- name: EXCERSISES/PING_PONG
  newName: zelhs/randomstring
  newTag: main-6df35bddf3131f525aab636d8e637a05fa2f8ed4
- name: EXCERSISES/RANDOM_STRING
  newName: zelhs/ping-pong-application
  newTag: main-6df35bddf3131f525aab636d8e637a05fa2f8ed4
- name: EXCERSISES/greeter
  newName: zelhs/greeter
  newTag: main-6df35bddf3131f525aab636d8e637a05fa2f8ed4
- name: EXERCISES/GET_STRING_SERVER
  newName: zelhs/get-string-server
  newTag: main-6df35bddf3131f525aab636d8e637a05fa2f8ed4
