apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./porsgresServices/HeadlessClusterIP.yml
  - ./porsgresServices/PostgresSecret.yml
  - ./porsgresServices/StatefullSetPorsgres.yml
  - ./manifest/ConfigMap.yml
  - ./manifest/HttpRoute.yml
  - ./manifest/Gateway.yml
  - ./manifest/DeploymentPong.yml
  - ./manifest/Deployment.yml
  - ./manifest/LogOutputClusterIP.yml
  - ./manifest/PingPongClusterIP.yml
  - ./persistentVolumes/persistentvolume.yaml
  - ./persistentVolumes/persistentvolumeclaim.yaml

  
images:
  - name: EXCERSISES/RANDOM_STRING
    newName: zelhs/ping-pong-application:4.1.1
  - name: EXCERSISES/PING_PONG
    newName: zelhs/randomstring:4.1.2
