apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: logoutput-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: ""
    http:
      paths:
      - path: /increasePingPongs
        pathType: Prefix
        backend:
          service:
            name: ping-pong-svc
            port:
              number: 2020
      - path: /pings
        pathType: Prefix
        backend:
          service:
            name: ping-pong-svc
            port:
              number: 2020
      - path: /
        pathType: Prefix
        backend:
          service:
            name: logoutput-svc
            port:
              number: 2345
